/**
 * Patches @homebridge/node-pty-prebuilt-multiarch gyp files to compile on
 * Windows without Spectre-mitigated libraries and without needing to run
 * GetCommitHash.bat / UpdateGenVersion.bat (shell scripts that fail in the
 * electron-rebuild environment).
 *
 * Run automatically via the `postinstall` npm script.
 * Safe to run multiple times (idempotent).
 */

const fs   = require('fs')
const path = require('path')

const PTY_ROOT = path.join(__dirname, '..', 'node_modules', '@homebridge', 'node-pty-prebuilt-multiarch')

if (!fs.existsSync(PTY_ROOT)) {
  console.log('[patch-pty-gyp] @homebridge/node-pty-prebuilt-multiarch not found, skipping.')
  process.exit(0)
}

// ── 1. binding.gyp — remove Spectre + guard:cf ───────────────────────────────
const bindingGypPath = path.join(PTY_ROOT, 'binding.gyp')
if (fs.existsSync(bindingGypPath)) {
  let src = fs.readFileSync(bindingGypPath, 'utf-8')
  if (src.includes('SpectreMitigation')) {
    src = src
      .replace(/\s*'msvs_configuration_attributes':\s*\{\s*'SpectreMitigation':\s*'Spectre'\s*\},/g, '')
      .replace(/\s*'\/guard:cf',/g, '')
      .replace(/\s*'\/ZH:SHA_256',/g, '')
      .replace(/\s*'VCLinkerTool':\s*\{\s*'AdditionalOptions':\s*\[\s*\]\s*\},/g, '')
    fs.writeFileSync(bindingGypPath, src)
    console.log('[patch-pty-gyp] Patched binding.gyp (removed Spectre / guard:cf)')
  }
}

// ── 2. winpty.gyp — replace bat commands + remove Spectre ────────────────────
const winptyGypPath = path.join(PTY_ROOT, 'deps', 'winpty', 'src', 'winpty.gyp')
if (fs.existsSync(winptyGypPath)) {
  let src = fs.readFileSync(winptyGypPath, 'utf-8')
  let changed = false

  if (src.includes('GetCommitHash.bat')) {
    src = src.replace(
      /'WINPTY_COMMIT_HASH%':\s*'<!\(cmd \/c "cd shared && GetCommitHash\.bat"\)'/g,
      "'WINPTY_COMMIT_HASH%': 'none'"
    )
    changed = true
  }

  if (src.includes('UpdateGenVersion.bat')) {
    src = src.replace(
      /'<!\(cmd \/c "cd shared && UpdateGenVersion\.bat <\(WINPTY_COMMIT_HASH\)"\)'/g,
      "'gen'"
    )
    changed = true
  }

  if (src.includes('SpectreMitigation')) {
    src = src
      .replace(/\s*'msvs_configuration_attributes':\s*\{\s*'SpectreMitigation':\s*'Spectre'\s*\},/g, '')
      .replace(/\s*'\/guard:cf',/g, '')
      .replace(/\s*'\/ZH:SHA_256',/g, '')
      .replace(/\s*'VCLinkerTool':\s*\{\s*'AdditionalOptions':\s*\[\s*\]\s*\},/g, '')
    changed = true
  }

  if (changed) {
    fs.writeFileSync(winptyGypPath, src)
    console.log('[patch-pty-gyp] Patched winpty.gyp (replaced bat commands + removed Spectre)')
  }
}

// ── 3. Generate GenVersion.h if missing ──────────────────────────────────────
const genDir    = path.join(PTY_ROOT, 'deps', 'winpty', 'src', 'gen')
const genHeader = path.join(genDir, 'GenVersion.h')
if (!fs.existsSync(genDir)) fs.mkdirSync(genDir, { recursive: true })
if (!fs.existsSync(genHeader)) {
  let version = '0.4.4-dev'
  try {
    const versionTxt = path.join(PTY_ROOT, 'deps', 'winpty', 'VERSION.txt')
    if (fs.existsSync(versionTxt)) version = fs.readFileSync(versionTxt, 'utf-8').trim()
  } catch { /* ignore */ }
  fs.writeFileSync(genHeader,
    `// AUTO-GENERATED BY patch-pty-gyp.js\n` +
    `const char GenVersion_Version[] = "${version}";\n` +
    `const char GenVersion_Commit[] = "none";\n`
  )
  console.log('[patch-pty-gyp] Created GenVersion.h')
}

console.log('[patch-pty-gyp] Done.')
